'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import {
  FileText,
  Plus,
  Printer,
  RefreshCw,
  Stethoscope,
  X,
} from 'lucide-react';
import { fallbackPackagesData } from '@/data/fallback';
import { useOverrides } from '@/context/PresentationOverridesContext';
import { usePricing } from '@/context/PricingContext';
import { ease } from '@/lib/motion';
import { useScrollReveal } from '@/lib/use-scroll-reveal';
import type { Package, PackageCategory } from '@/types/content';
import { PriceBadge } from './PriceBadge';

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
const HMC_LOGO_COLOURED = `${BASE_PATH}/brand/hmc-logo-coloured.png`;

/**
 * Phase 2.4S — Package Template Simulator (§13.6).
 *
 * Visual chrome refined to match the real HMC printable documents
 * generated by hmc_invoice.py (in the repo root). Both panels now
 * carry the official letterhead (coloured logo + 6-line address
 * block + red rule), the MED_BLUE / LIGHT_BLUE patient grid, blue
 * section bars + zebra rows on the invoice, GRAND TOTAL bar, and
 * the centred footer + 24-hour hotline line.
 *
 * Simulator logic, package selection, default-load HMC-GI-03, the
 * "Load Package Template" gate, pricing, scenarios, packages.json,
 * <PriceBadge>, and override-aware state are all unchanged from
 * 2.4Q / 2.4R.
 *
 * Locked rules respected:
 *   - No invented prices — uses pkg.prices via existing <PriceBadge>
 *   - No invented patient identity — defaults are obvious placeholders
 *   - Scenario A continues to render "To be agreed"
 *   - No Scenario A/B/C audience labels
 *   - No localStorage / persistence
 *   - No bank details / IBAN (excluded from audience-visible deck)
 *   - Override-aware: respects Control Mode applyPackages()
 */

/* ───────────────── HMC palette (from hmc_invoice.py) ───────────────── */

const DARK_BLUE = '#1B3A5C';
const MED_BLUE = '#2E75B6';
const LIGHT_BLUE = '#EBF3FB';
const RED = '#C00000';
const GREY_RULE = '#DDDDDD';

/* ───────────────── Print stylesheet (shared) ─────────────────
 * Single source of truth for the @media print rule used by both
 * print preview modals. Hides every element on the page except the
 * portalled `.hmc-print-root` and strips the sheet's modal chrome
 * down to bare paper-on-A4.
 *
 * Phase 2.4U.1 fix:
 *   - The 2.4U version used `visibility: hidden` which still keeps
 *     elements in the box model, so the simulator's article wrapper
 *     (py-20 md:py-24) emitted 4–5 blank pages above the modal.
 *   - Switched to `display: none` so hidden elements are removed
 *     from layout entirely.
 *   - Both modals now portal into document.body via createPortal so
 *     `.hmc-print-root` is a direct child of <body>, letting
 *     `body > *:not(.hmc-print-root)` cleanly hide everything else.
 *   - Strip sheet padding in print; rely on @page margin only.
 *   - break-inside: avoid on letterhead, patient grid, GRAND TOTAL
 *     bar, and footer so key blocks never split mid-row.
 */
const PRINT_STYLE = `
@media print {
  @page { size: A4; margin: 10mm; }

  /* Hide everything except the print root. */
  body > *:not(.hmc-print-root) { display: none !important; }

  /* The portalled modal becomes the only printable thing on the page. */
  .hmc-print-root {
    position: static !important;
    inset: auto !important;
    width: 100% !important;
    height: auto !important;
    margin: 0 !important;
    padding: 0 !important;
    background: white !important;
    overflow: visible !important;
    backdrop-filter: none !important;
    display: block !important;
    color: #000 !important;
  }

  /* All children of the print root: also strip modal chrome. */
  .hmc-print-root .hmc-print-controls { display: none !important; }

  /* The A4 sheet itself: drop modal-only padding/shadow so @page margin
     is the only space around the content. */
  .hmc-print-root .hmc-print-sheet {
    box-shadow: none !important;
    max-width: none !important;
    width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
    background: white !important;
    color: #000 !important;
  }

  /* Key blocks that must never split mid-row. */
  .hmc-print-no-break {
    break-inside: avoid !important;
    page-break-inside: avoid !important;
  }

  /* Tighten line-heights a notch for printable density. */
  .hmc-print-sheet * {
    color: #000 !important;
  }
}
`;

/* ───────────────── Invoice-style scenario-aware total text ─────────────────
 * Phase 2.4T — the GRAND TOTAL row inside the invoice document should read
 * as plain white invoice-style bold text, not a coloured PriceBadge chip.
 * This helper consumes the SAME usePricing() context PriceBadge uses, so
 * Scenario A continues to render "To be agreed" and Scenarios B/C render
 * the catalogue figure. Pricing logic, PriceBadge, and scenario state are
 * untouched.
 */
function InvoiceTotalValue({ pkg }: { pkg: Package }) {
  const { scenario } = usePricing();
  const text =
    scenario === 'A'
      ? 'To be agreed'
      : `€${scenario === 'B' ? pkg.prices.B : pkg.prices.C}`;
  return (
    <AnimatePresence mode="wait">
      <motion.span
        key={`${scenario}-${text}`}
        initial={{ opacity: 0, y: 4 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -4 }}
        transition={{ duration: 0.4, ease: ease.premium }}
        className="font-sans text-base font-bold uppercase tracking-[0.05em] text-white md:text-lg"
      >
        {text}
      </motion.span>
    </AnimatePresence>
  );
}

/* ───────────────── Field shapes ───────────────── */

interface VitalsBlock {
  bloodPressure: string;
  pulseRate: string;
  oxygenSaturation: string;
  temperature: string;
  respiratoryRate: string;
  gcs: string;
}

interface ReportFields {
  // Identity / references
  patientInitials: string;
  adacRef: string;
  hmcRef: string;
  date: string;

  // Patient / visit metadata (matches Python patient table)
  toInsurance: string;
  nationality: string;
  dob: string;
  gender: string;
  dateOfAdmission: string;
  dateOfDischarge: string;

  // Clinical sections
  complaint: string;
  pastHistory: string;
  vitals: VitalsBlock;
  generalExamination: string;
  localExamination: string;
  investigations: string[];
  diagnosis: string;
  management: string;
  initialTreatmentPlan: string;
  medications: string[];
  managementOutcome: string;
  dischargeInstructions: string;
  dischargeMedications: string[];
  followUp: string;
}

type CategoryClinical = Omit<
  ReportFields,
  | 'patientInitials'
  | 'adacRef'
  | 'hmcRef'
  | 'date'
  | 'toInsurance'
  | 'nationality'
  | 'dob'
  | 'gender'
  | 'dateOfAdmission'
  | 'dateOfDischarge'
>;

/* ───────────────── Category templates (9) ─────────────────
 * Each template provides defaults for every clinical section in the
 * 14-section medical-report shape. Vitals are 6 named lines. Lists
 * (investigations / medications / discharge medications) are arrays.
 */

const CATEGORY_TEMPLATES: Record<string, CategoryClinical> = {
  GI: {
    complaint:
      'Acute watery diarrhoea, nausea / vomiting, mild abdominal cramps over the past 24 hours.',
    pastHistory:
      'No chronic GI illness reported. No regular medications. No known allergies.',
    vitals: {
      bloodPressure: '124 / 78 mmHg',
      pulseRate: '92 / min',
      oxygenSaturation: '98 % on room air',
      temperature: '37.6 °C',
      respiratoryRate: '16 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert, oriented · mild dehydration · pale conjunctivae · no rash · peripheral perfusion adequate.',
    localExamination:
      'Abdomen soft, mild diffuse tenderness, no rigidity, no rebound, no guarding, bowel sounds present.',
    investigations: [
      'Bedside vital signs and hydration assessment.',
      'Random blood glucose by glucometer.',
      'Labs only if included in package scope (e.g. CBC, CRP, electrolytes).',
    ],
    diagnosis: 'Acute gastroenteritis with mild dehydration · ICD-10 A09.',
    management:
      'Oral and IV rehydration · symptomatic anti-emetic and anti-diarrhoeal · close observation for response.',
    initialTreatmentPlan:
      'IV cannula sited · 1–2 IV bags (Ringer / saline) · IM/IV anti-emetic · oral anti-diarrhoeal · monitor 60–120 min.',
    medications: [
      'IV crystalloid 1–2 bags as per package scope.',
      'IM / IV anti-emetic single dose.',
      'Oral anti-diarrhoeal as indicated.',
      'Oral rehydration salts on discharge.',
    ],
    managementOutcome:
      'Symptomatic improvement after IV rehydration and anti-emetic; tolerating oral fluids on reassessment; haemodynamically stable.',
    dischargeInstructions:
      'Oral rehydration, small frequent fluids, bland diet, avoid dairy 24–48 h. Return if vomiting persists or signs of severe dehydration.',
    dischargeMedications: [
      'Oral rehydration salts — as directed for 24–48 h.',
      'Oral anti-diarrhoeal — if symptoms persist.',
      'Paracetamol oral — for fever or pain.',
    ],
    followUp: 'Phone check at 12 h. Return to clinic if not improving within 24 h.',
  },
  RX: {
    complaint:
      'Cough, fever, sore throat, with or without shortness of breath, over the past 48–72 hours.',
    pastHistory:
      'No chronic respiratory illness. No regular medications. No known drug allergies.',
    vitals: {
      bloodPressure: '122 / 76 mmHg',
      pulseRate: '96 / min',
      oxygenSaturation: '97 % on room air',
      temperature: '38.4 °C',
      respiratoryRate: '18 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · febrile · mildly flushed · no respiratory distress at rest · peripheral perfusion intact.',
    localExamination:
      'Throat erythematous, tonsils mildly enlarged, no exudate · cervical lymph nodes mildly tender · chest auscultation as indicated.',
    investigations: [
      'Bedside vitals and SpO2.',
      'Throat assessment.',
      'Labs / imaging only if included in package scope.',
    ],
    diagnosis: 'Acute upper respiratory tract infection / pharyngotonsillitis · ICD-10 J06.',
    management:
      'Symptomatic antipyretic and analgesic; antibiotic if clinically indicated; supportive measures.',
    initialTreatmentPlan:
      'IM or oral antipyretic · oral analgesic · nebulizer session if package includes it · hydration advice.',
    medications: [
      'Antipyretic (paracetamol) oral / IM as per package scope.',
      'Oral analgesic for throat pain.',
      'Antibiotic course if clinically indicated.',
    ],
    managementOutcome:
      'Fever responding to antipyretic; oxygen saturation maintained on room air; no respiratory distress on reassessment.',
    dischargeInstructions:
      'Hydration, rest, antipyretic for fever above 38 °C. Return if shortness of breath, persistent high fever, or worsening symptoms.',
    dischargeMedications: [
      'Antipyretic oral — every 6 h as needed.',
      'Oral analgesic — as needed for throat pain.',
      'Antibiotic course oral — complete the prescribed duration.',
    ],
    followUp:
      'Phone check at 24 h. Return to clinic if no improvement within 72 h.',
  },
  WD: {
    complaint:
      'Open wound / laceration / minor trauma sustained in the past hours; bleeding controlled at presentation.',
    pastHistory:
      'Tetanus immunisation status reviewed. No known coagulopathy. No regular anticoagulant medications.',
    vitals: {
      bloodPressure: '126 / 78 mmHg',
      pulseRate: '84 / min',
      oxygenSaturation: '99 % on room air',
      temperature: '36.9 °C',
      respiratoryRate: '14 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert, comfortable, no signs of systemic infection or shock; peripheral perfusion intact.',
    localExamination:
      'Wound site inspected, depth and length documented, neurovascular status distal to the wound intact, no foreign body palpable.',
    investigations: [
      'Bedside wound inspection and photo documentation.',
      'X-Ray only if included in package scope (e.g. suspected foreign body).',
    ],
    diagnosis:
      'Laceration · sutured / dressed · ICD-10 by anatomical site (e.g. S01 head, S61 wrist / hand).',
    management:
      'Wound cleaning · local anaesthetic infiltration · suturing or steri-strip as appropriate · dressing per protocol.',
    initialTreatmentPlan:
      'Antiseptic prep · local anaesthetic infiltration · suturing per package scope · sterile dressing · neurovascular recheck.',
    medications: [
      'Local anaesthetic infiltration.',
      'Oral analgesic for post-procedure pain.',
      'Tetanus prophylaxis if indicated.',
    ],
    managementOutcome:
      'Wound closed and dressed; haemostasis achieved; neurovascular status preserved on reassessment.',
    dischargeInstructions:
      'Keep wound dry 24 h, return for suture removal per anatomical site, return earlier if signs of infection.',
    dischargeMedications: [
      'Oral analgesic — as needed.',
      'Topical antiseptic — at each dressing change.',
      'Antibiotic course if clinically indicated.',
    ],
    followUp:
      'Suture removal visit at 3–14 days depending on anatomical site. Phone check at 48 h.',
  },
  OR: {
    complaint:
      'Acute musculoskeletal pain / suspected sprain or fracture following injury within the past 24 hours.',
    pastHistory:
      'No prior fractures at the same site. No regular medications. No known anaesthetic allergy.',
    vitals: {
      bloodPressure: '128 / 80 mmHg',
      pulseRate: '88 / min',
      oxygenSaturation: '98 % on room air',
      temperature: '37.0 °C',
      respiratoryRate: '14 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · in mild pain · no signs of systemic compromise · peripheral perfusion intact distal to the affected limb.',
    localExamination:
      'Affected limb / joint examined; swelling and range of motion documented; neurovascular status distal intact; weight-bearing status noted.',
    investigations: [
      'Clinical examination of the affected limb / joint.',
      'X-Ray of the affected site if included in package scope.',
    ],
    diagnosis:
      'Soft tissue injury / sprain / suspected fracture · ICD-10 by anatomical site (e.g. S93 ankle).',
    management:
      'Ice · elevation · compression · immobilisation (splint / sling / plaster) per package scope; oral analgesia.',
    initialTreatmentPlan:
      'X-Ray (if scope) · cold compress · oral analgesic · immobilisation device applied · neurovascular recheck post-immobilisation.',
    medications: [
      'Oral analgesic (paracetamol / NSAID).',
      'Anti-inflammatory if indicated.',
    ],
    managementOutcome:
      'Pain controlled; affected limb immobilised; neurovascular status preserved on reassessment.',
    dischargeInstructions:
      'Elevation; ice 20 min every 2–3 h for 24–48 h; weight-bearing as advised; return if neurovascular compromise.',
    dischargeMedications: [
      'Oral analgesic — every 6 h as needed.',
      'Anti-inflammatory — if no contraindication.',
    ],
    followUp:
      'Re-assessment in 5–7 days. Earlier if pain or swelling worsens.',
  },
  EN: {
    complaint:
      'Ear pain / discharge / blocked sensation; or sore throat with difficulty swallowing.',
    pastHistory:
      'No prior ear surgery. No regular medications. No known drug allergies.',
    vitals: {
      bloodPressure: '124 / 78 mmHg',
      pulseRate: '86 / min',
      oxygenSaturation: '98 % on room air',
      temperature: '37.4 °C',
      respiratoryRate: '14 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · mildly uncomfortable · no respiratory distress · peripheral perfusion intact.',
    localExamination:
      'Ear canal inspected with otoscope; tympanic membrane assessed; throat and tonsils examined; cervical lymph nodes palpated.',
    investigations: [
      'Otoscopic examination.',
      'Throat inspection.',
    ],
    diagnosis:
      'Acute otitis externa / media · or acute pharyngotonsillitis · ICD-10 H60 / H66 / J03.',
    management:
      'Ear cleaning / wash if indicated · topical and oral medication as per package scope.',
    initialTreatmentPlan:
      'Ear cleaning · topical ear drops · oral analgesic · antibiotic if clinically indicated.',
    medications: [
      'Topical ear drops as per package scope.',
      'Oral analgesic.',
      'Antibiotic course if clinically indicated.',
    ],
    managementOutcome:
      'Pain settled with analgesia; ear canal cleared where applicable; reassurance given to traveler.',
    dischargeInstructions:
      'Keep ear dry; avoid swimming until follow-up; return if hearing loss persists or neurological signs develop.',
    dischargeMedications: [
      'Topical ear preparation — as directed.',
      'Oral analgesic — as needed.',
      'Antibiotic course — complete duration if prescribed.',
    ],
    followUp: 'Re-assessment in 7 days. Earlier if symptoms worsen.',
  },
  DN: {
    complaint: 'Acute dental pain / dental trauma / suspected dental abscess.',
    pastHistory:
      'Dental history reviewed. No known dental allergies. No regular medications.',
    vitals: {
      bloodPressure: '122 / 78 mmHg',
      pulseRate: '84 / min',
      oxygenSaturation: '98 % on room air',
      temperature: '37.2 °C',
      respiratoryRate: '14 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · mildly uncomfortable from pain · no airway compromise · peripheral perfusion intact.',
    localExamination:
      'Oral cavity inspected; affected tooth identified; gingival inspection; no swelling tracking to facial spaces.',
    investigations: [
      'Clinical dental examination.',
      'Dental X-Ray if included in package scope.',
    ],
    diagnosis:
      'Acute dental pain · pulpitis / periapical pathology · ICD-10 K04.',
    management:
      'Pain control · drainage if abscess and within scope · temporary filling or extraction per selected package.',
    initialTreatmentPlan:
      'Local anaesthetic · drainage / temporary filling / extraction per scope · post-procedure analgesia.',
    medications: [
      'Local anaesthetic infiltration.',
      'Oral analgesic for post-procedure pain.',
      'Antibiotic course if clinically indicated.',
    ],
    managementOutcome:
      'Pain controlled; affected tooth addressed per scope; no signs of spreading infection.',
    dischargeInstructions:
      'Soft diet 24 h; avoid hot fluids; return if swelling spreads or fever develops.',
    dischargeMedications: [
      'Oral analgesic — as needed.',
      'Antibiotic course — complete duration if prescribed.',
    ],
    followUp:
      'Dental follow-up appointment as scheduled. Phone check at 48 h.',
  },
  DR: {
    complaint:
      'Skin rash / itching / allergic reaction / insect bite / sunburn over the past hours.',
    pastHistory:
      'No known drug allergies. No history of severe systemic reactions. No regular medications.',
    vitals: {
      bloodPressure: '120 / 76 mmHg',
      pulseRate: '88 / min',
      oxygenSaturation: '99 % on room air',
      temperature: '37.1 °C',
      respiratoryRate: '14 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · no respiratory distress · no facial / oral swelling · peripheral perfusion intact.',
    localExamination:
      'Affected skin area examined; distribution and morphology noted; no signs of anaphylaxis; no airway compromise.',
    investigations: [
      'Clinical skin examination.',
      'Vital signs monitoring.',
    ],
    diagnosis:
      'Acute allergic reaction / urticaria / contact dermatitis · ICD-10 L50 / T78.',
    management:
      'Antihistamine (IM / IV / oral) · corticosteroid if package scope · topical preparation as indicated.',
    initialTreatmentPlan:
      'Antihistamine first-line · corticosteroid if scope · topical cream · observation for response.',
    medications: [
      'Antihistamine (IM / IV / oral).',
      'Corticosteroid course if within package scope.',
      'Topical anti-itch / corticosteroid cream.',
    ],
    managementOutcome:
      'Symptoms responding to antihistamine; no progression to airway involvement; haemodynamically stable.',
    dischargeInstructions:
      'Avoid known triggers; use prescribed cream; return immediately if shortness of breath, swelling of face or throat.',
    dischargeMedications: [
      'Oral antihistamine — as directed.',
      'Topical cream — twice daily.',
      'Oral corticosteroid course — if prescribed.',
    ],
    followUp:
      'Phone check at 24 h. Return to clinic if rash spreads or fails to improve within 72 h.',
  },
  EY: {
    complaint: 'Acute eye redness / irritation / foreign body sensation / discharge.',
    pastHistory:
      'No prior eye surgery. No known ocular allergies. No regular eye medications.',
    vitals: {
      bloodPressure: '122 / 78 mmHg',
      pulseRate: '84 / min',
      oxygenSaturation: '99 % on room air',
      temperature: '36.9 °C',
      respiratoryRate: '14 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · comfortable · no systemic compromise · peripheral perfusion intact.',
    localExamination:
      'Visual acuity recorded · external eye examination · conjunctiva assessed · cornea inspected with magnification.',
    investigations: [
      'Visual acuity test.',
      'External eye examination.',
      'Fluorescein assessment if included in package scope.',
    ],
    diagnosis:
      'Acute conjunctivitis / corneal foreign body · ICD-10 H10 / S05.',
    management:
      'Eye wash · topical antibiotic eye drops · foreign body removal under magnification if scope.',
    initialTreatmentPlan:
      'Eye irrigation · topical antibiotic · foreign body removal if scope · post-removal reassessment.',
    medications: [
      'Topical antibiotic eye drops.',
      'Lubricant eye drops.',
      'Oral analgesic if indicated.',
    ],
    managementOutcome:
      'Symptoms settling; visual acuity preserved; no corneal injury identified on reassessment.',
    dischargeInstructions:
      'No eye rubbing; sunglasses for comfort; return if pain, vision loss, or photophobia worsens.',
    dischargeMedications: [
      'Topical antibiotic eye drops — 4× daily.',
      'Lubricant eye drops — as needed.',
    ],
    followUp: 'Re-assessment in 48–72 h.',
  },
  CR: {
    complaint:
      'Chest pain / palpitations / hypertensive symptoms / syncope — outpatient-screening presentation.',
    pastHistory:
      'Cardiac history reviewed. Current medications recorded. No known cardiac allergies.',
    vitals: {
      bloodPressure: '148 / 92 mmHg',
      pulseRate: '96 / min',
      oxygenSaturation: '97 % on room air',
      temperature: '36.9 °C',
      respiratoryRate: '16 / min',
      gcs: '15',
    },
    generalExamination:
      'Alert · no acute distress · peripheral perfusion intact · no peripheral oedema · neurological status grossly intact.',
    localExamination:
      'Cardiac auscultation · peripheral pulses · ECG performed at first contact · neurological screen.',
    investigations: [
      '12-lead ECG.',
      'Troponin if included in package scope.',
      'Continuous vital signs monitoring during observation.',
    ],
    diagnosis:
      'Outpatient cardiac assessment · low-risk chest pain / hypertensive urgency · ICD-10 R07 / I10.',
    management:
      'Anti-hypertensive titration if indicated · oral analgesia · cardiac monitoring per package scope.',
    initialTreatmentPlan:
      'ECG · serial vitals · anti-hypertensive · monitoring · escalate to §11 pathway if red flags appear.',
    medications: [
      'Oral anti-hypertensive as per scope.',
      'Oral analgesic / anti-anginal if indicated.',
    ],
    managementOutcome:
      'Symptoms settling on conservative management; ECG and vital signs reassuring; no red flags identified.',
    dischargeInstructions:
      'Strict return precautions — chest pain, shortness of breath, syncope, palpitations → return immediately or call emergency.',
    dischargeMedications: [
      'Oral anti-hypertensive — as directed.',
      'Oral analgesic / anti-anginal — as needed.',
    ],
    followUp:
      'Cardiology outpatient referral within 7 days. Phone check at 24 h.',
  },
};

/* ───────────────── Helpers ───────────────── */

function makeDefaults(pkg: Package | null): ReportFields {
  const today = new Date().toISOString().slice(0, 10);
  const code = (pkg?.code ?? '').toLowerCase();
  const familyKey =
    ['GI', 'IV', 'RX', 'WD', 'OR', 'EN', 'DN', 'DR', 'EY', 'CR'].find((k) =>
      code.includes(`-${k.toLowerCase()}-`)
    ) ?? 'GI';
  // IV packages reuse the GI clinical template (they are linked clinically and live in the GI category).
  const templateKey = familyKey === 'IV' ? 'GI' : familyKey;
  const t = CATEGORY_TEMPLATES[templateKey] ?? CATEGORY_TEMPLATES.GI;

  return {
    patientInitials: 'M.K.',
    adacRef: 'ADAC-DEMO-REF',
    hmcRef: 'HMC-DEMO-CASE',
    date: today,
    toInsurance: 'ADAC AG Holder Assistance',
    nationality: '—',
    dob: '—',
    gender: '—',
    dateOfAdmission: today,
    dateOfDischarge: today,
    ...t,
    // Clone arrays so editing one package's defaults doesn't mutate the template object.
    investigations: [...t.investigations],
    medications: [...t.medications],
    dischargeMedications: [...t.dischargeMedications],
    vitals: { ...t.vitals },
  };
}

function splitIncluded(included?: string): string[] {
  if (!included) return [];
  return included.split('·').map((s) => s.trim()).filter(Boolean);
}

/* ───────────────── Shared document chrome (matches hmc_invoice.py) ───────────────── */

/**
 * Official HMC letterhead band — coloured logo on the left, 6 address
 * lines right-aligned in DARK_BLUE, red horizontal rule below.
 */
function HMCLetterhead() {
  return (
    <div className="hmc-print-no-break relative -mx-5 -mt-5 mb-4 bg-white px-5 pt-4 md:-mx-7 md:-mt-7 md:px-8 md:pt-5">
      <div className="flex items-start justify-between gap-4">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={HMC_LOGO_COLOURED}
          alt=""
          className="h-12 w-auto object-contain md:h-14"
          aria-hidden
        />
        <div className="text-right">
          <p
            className="font-sans text-[11px] font-bold uppercase tracking-[0.05em] md:text-[12px]"
            style={{ color: DARK_BLUE }}
          >
            Hurghada Medical Center
          </p>
          <p
            className="mt-0.5 text-[9px] uppercase tracking-[0.04em] md:text-[10px]"
            style={{ color: DARK_BLUE }}
          >
            Building 306, Elkawther Street, Hurghada, Egypt
          </p>
          <p
            className="text-[9px] uppercase tracking-[0.04em] md:text-[10px]"
            style={{ color: DARK_BLUE }}
          >
            Website: www.hurghadamedicalcenter.com
          </p>
          <p
            className="text-[9px] uppercase tracking-[0.04em] md:text-[10px]"
            style={{ color: DARK_BLUE }}
          >
            Email: info@hurghadamedicalcenter.com
          </p>
          <p
            className="text-[9px] uppercase tracking-[0.04em] md:text-[10px]"
            style={{ color: DARK_BLUE }}
          >
            Tel: +2 012 0388 1077 / +2 012 0388 2077
          </p>
          <p
            className="text-[9px] uppercase tracking-[0.04em] md:text-[10px]"
            style={{ color: DARK_BLUE }}
          >
            Tel&amp;Fax: +2 065 340 3500
          </p>
        </div>
      </div>
      {/* RED 2pt rule */}
      <div
        className="mt-3 h-[2px] w-full"
        style={{ background: RED }}
      />
    </div>
  );
}

/** Centred document title in DARK_BLUE bold. */
function DocumentTitle({ title }: { title: string }) {
  return (
    <p
      className="relative mb-4 text-center text-base font-bold uppercase tracking-[0.18em] md:text-lg"
      style={{ color: DARK_BLUE }}
    >
      {title}
    </p>
  );
}

/** Diagonal demo watermark. */
function DemoWatermark() {
  return (
    <span
      aria-hidden
      className="pointer-events-none absolute inset-0 flex items-center justify-center"
      style={{
        transform: 'rotate(-22deg)',
        fontSize: 'clamp(1.5rem, 4.5vw, 3.5rem)',
        fontFamily: 'var(--font-playfair), Georgia, serif',
        color: 'rgba(201, 169, 97, 0.14)',
        fontWeight: 700,
        letterSpacing: '0.1em',
      }}
    >
      DEMO PREVIEW · NO REAL PATIENT DATA
    </span>
  );
}

/**
 * Patient / visit metadata grid — mirrors Python's `_draw_patient_table`.
 * MED_BLUE label cells (white text), LIGHT_BLUE value cells (black text),
 * full-width TO row at the bottom.
 */
interface MetaRow {
  l1: string;
  v1: string;
  l2: string;
  v2: string;
  edit1?: (v: string) => void;
  edit2?: (v: string) => void;
}

function PatientMetaGrid({
  rows,
  toText,
}: {
  rows: MetaRow[];
  toText: string;
}) {
  return (
    <div className="hmc-print-no-break relative overflow-hidden border" style={{ borderColor: '#000' }}>
      <table className="w-full border-collapse text-[11px] md:text-[12px]">
        <tbody>
          {rows.map((r, i) => (
            <tr key={i}>
              {/* Pair 1 */}
              <td
                className="px-2 py-1.5 font-sans font-bold uppercase tracking-[0.05em]"
                style={{
                  background: MED_BLUE,
                  color: '#fff',
                  width: '24%',
                }}
              >
                {r.l1}
              </td>
              <td
                className="px-2 py-1"
                style={{
                  background: LIGHT_BLUE,
                  color: '#000',
                  width: '26%',
                }}
              >
                {r.edit1 ? (
                  <input
                    type="text"
                    value={r.v1}
                    onChange={(e) => r.edit1?.(e.target.value)}
                    className="w-full border-none bg-transparent p-0 text-[11px] outline-none md:text-[12px]"
                    style={{ color: '#000' }}
                  />
                ) : (
                  <span>{r.v1 || '—'}</span>
                )}
              </td>
              {/* Pair 2 */}
              <td
                className="px-2 py-1.5 font-sans font-bold uppercase tracking-[0.05em]"
                style={{
                  background: MED_BLUE,
                  color: '#fff',
                  width: '24%',
                }}
              >
                {r.l2}
              </td>
              <td
                className="px-2 py-1"
                style={{
                  background: LIGHT_BLUE,
                  color: '#000',
                  width: '26%',
                }}
              >
                {r.edit2 ? (
                  <input
                    type="text"
                    value={r.v2}
                    onChange={(e) => r.edit2?.(e.target.value)}
                    className="w-full border-none bg-transparent p-0 text-[11px] outline-none md:text-[12px]"
                    style={{ color: '#000' }}
                  />
                ) : (
                  <span>{r.v2 || '—'}</span>
                )}
              </td>
            </tr>
          ))}
          <tr>
            <td
              className="px-2 py-1.5 font-sans font-bold uppercase tracking-[0.05em]"
              style={{ background: MED_BLUE, color: '#fff', width: '24%' }}
            >
              TO:
            </td>
            <td
              colSpan={3}
              className="px-2 py-1.5 font-bold"
              style={{ background: LIGHT_BLUE, color: DARK_BLUE }}
            >
              {toText}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

/**
 * Centred footer line + 24-hour hotline (from the brief, not in Python).
 */
function HMCFooter() {
  return (
    <div className="hmc-print-no-break relative mt-6">
      <div className="h-px w-full" style={{ background: RED }} />
      <p
        className="mt-2 text-center text-[8.5px] uppercase tracking-[0.04em] md:text-[9.5px]"
        style={{ color: DARK_BLUE }}
      >
        Hurghada Medical Center &nbsp;|&nbsp; Building 306, Elkawther Street,
        Hurghada, Egypt &nbsp;|&nbsp; Tel: +2 012 0388 1077 &nbsp;|&nbsp;
        info@hurghadamedicalcenter.com
      </p>
      <p
        className="mt-1 text-center text-[8.5px] font-bold uppercase tracking-[0.06em] md:text-[9.5px]"
        style={{ color: RED }}
      >
        24 HOURS MEDICAL ASSISTANCE HOTLINES: +2 012 0388 1077 — +2 012 0388 2077
      </p>
    </div>
  );
}

/* ───────────────── Report Panel ───────────────── */

interface ReportPanelProps {
  pkg: Package;
  fields: ReportFields;
  setField: <K extends keyof ReportFields>(k: K, v: ReportFields[K]) => void;
  setVital: <K extends keyof VitalsBlock>(k: K, v: string) => void;
  setListItem: (
    key: 'investigations' | 'medications' | 'dischargeMedications',
    index: number,
    value: string
  ) => void;
  addListItem: (
    key: 'investigations' | 'medications' | 'dischargeMedications'
  ) => void;
  removeListItem: (
    key: 'investigations' | 'medications' | 'dischargeMedications',
    index: number
  ) => void;
  onOpenPrintPreview: () => void;
}

function ReportPanel({
  pkg,
  fields,
  setField,
  setVital,
  setListItem,
  addListItem,
  removeListItem,
  onOpenPrintPreview,
}: ReportPanelProps) {
  return (
    <div
      className="overflow-hidden rounded-sm border border-white/10 bg-navy/40 backdrop-blur-sm"
      aria-label="Editable medical report template"
    >
      {/* Outer dark chrome label band */}
      <header
        className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-2.5"
        style={{ background: 'var(--theme-badge-bg)' }}
      >
        <div className="flex items-center gap-2">
          <Stethoscope size={14} style={{ color: 'var(--theme-badge-text)' }} />
          <p
            className="font-mono text-[10px] uppercase tracking-[0.32em]"
            style={{ color: 'var(--theme-badge-text)' }}
          >
            Editable Medical Report
          </p>
        </div>
        <div className="flex items-center gap-3">
          <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-ice/70">
            {pkg.code}
          </p>
          <button
            type="button"
            onClick={onOpenPrintPreview}
            className="inline-flex items-center gap-1.5 rounded-sm border px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.22em] transition-colors"
            style={{
              borderColor: 'var(--theme-accent)',
              background: 'var(--theme-badge-bg)',
              color: 'var(--theme-badge-text)',
            }}
          >
            <Printer size={12} />
            Print Preview
          </button>
        </div>
      </header>

      {/* White document sheet */}
      <div className="relative bg-white p-5 text-black md:p-7">
        <DemoWatermark />

        <HMCLetterhead />

        <DocumentTitle title="Medical Report" />

        {/* Phase 2.4U — metadata grid is now READ-ONLY display.
            The single edit surface is the shared Patient / Case Data
            panel above the documents. */}
        <PatientMetaGrid
          rows={[
            { l1: 'Your ref.',          v1: fields.adacRef,           l2: 'OUR Ref No:',     v2: fields.hmcRef },
            { l1: 'Patient:',           v1: fields.patientInitials,   l2: 'Date of Birth:',  v2: fields.dob },
            { l1: 'Nationality:',       v1: fields.nationality,       l2: 'Gender:',         v2: fields.gender },
            { l1: 'Date of Admission:', v1: fields.dateOfAdmission,   l2: 'Date of Discharge:', v2: fields.dateOfDischarge },
            { l1: 'Package Code:',      v1: pkg.code,                 l2: 'Date of Visit:',  v2: fields.date },
            { l1: 'Package Name:',      v1: pkg.name,                 l2: 'Document Type:',  v2: 'Medical Report' },
          ]}
          toText={fields.toInsurance}
        />

        {/* Clinical sections */}
        <div className="relative mt-5 space-y-4">
          <DocSection label="Complaint">
            <DocTextarea
              value={fields.complaint}
              onChange={(v) => setField('complaint', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Past History">
            <DocTextarea
              value={fields.pastHistory}
              onChange={(v) => setField('pastHistory', v)}
              rows={2}
            />
          </DocSection>

          {/* Vitals — 6 separately editable named lines */}
          <DocSection label="Emergency Consultation — Vital Signs">
            <div className="grid grid-cols-1 gap-y-1 text-[12px] md:grid-cols-2 md:gap-x-6 md:text-[13px]">
              <VitalRow
                label="Blood Pressure"
                value={fields.vitals.bloodPressure}
                onChange={(v) => setVital('bloodPressure', v)}
              />
              <VitalRow
                label="Pulse Rate"
                value={fields.vitals.pulseRate}
                onChange={(v) => setVital('pulseRate', v)}
              />
              <VitalRow
                label="Oxygen Saturation"
                value={fields.vitals.oxygenSaturation}
                onChange={(v) => setVital('oxygenSaturation', v)}
              />
              <VitalRow
                label="Temperature"
                value={fields.vitals.temperature}
                onChange={(v) => setVital('temperature', v)}
              />
              <VitalRow
                label="Respiratory Rate"
                value={fields.vitals.respiratoryRate}
                onChange={(v) => setVital('respiratoryRate', v)}
              />
              <VitalRow
                label="GCS"
                value={fields.vitals.gcs}
                onChange={(v) => setVital('gcs', v)}
              />
            </div>
          </DocSection>

          <DocSection label="General Examination">
            <DocTextarea
              value={fields.generalExamination}
              onChange={(v) => setField('generalExamination', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Local / System Examination">
            <DocTextarea
              value={fields.localExamination}
              onChange={(v) => setField('localExamination', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Investigations">
            <EditableList
              items={fields.investigations}
              onChange={(i, v) => setListItem('investigations', i, v)}
              onAdd={() => addListItem('investigations')}
              onRemove={(i) => removeListItem('investigations', i)}
            />
          </DocSection>

          <DocSection label="Diagnosis / Problem List">
            <DocTextarea
              value={fields.diagnosis}
              onChange={(v) => setField('diagnosis', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Management">
            <DocTextarea
              value={fields.management}
              onChange={(v) => setField('management', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Initial Treatment Plan">
            <DocTextarea
              value={fields.initialTreatmentPlan}
              onChange={(v) => setField('initialTreatmentPlan', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Medications">
            <EditableList
              items={fields.medications}
              onChange={(i, v) => setListItem('medications', i, v)}
              onAdd={() => addListItem('medications')}
              onRemove={(i) => removeListItem('medications', i)}
            />
          </DocSection>

          <DocSection label="Management Outcome">
            <DocTextarea
              value={fields.managementOutcome}
              onChange={(v) => setField('managementOutcome', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Discharge Instructions">
            <DocTextarea
              value={fields.dischargeInstructions}
              onChange={(v) => setField('dischargeInstructions', v)}
              rows={2}
            />
          </DocSection>

          <DocSection label="Discharge Medications">
            <EditableList
              items={fields.dischargeMedications}
              onChange={(i, v) => setListItem('dischargeMedications', i, v)}
              onAdd={() => addListItem('dischargeMedications')}
              onRemove={(i) => removeListItem('dischargeMedications', i)}
            />
          </DocSection>

          <DocSection label="Follow-up Plan">
            <DocTextarea
              value={fields.followUp}
              onChange={(v) => setField('followUp', v)}
              rows={2}
            />
          </DocSection>
        </div>

        {/* Doctor / operator review note */}
        <div
          className="relative mt-6 border-l-2 bg-ice/60 px-3 py-2 text-[11px] leading-relaxed text-gray-700 md:text-[12px]"
          style={{ borderColor: DARK_BLUE }}
        >
          Doctor / operator review required before submission. Template
          preview; not a final clinical document.
        </div>

        <HMCFooter />

        <p className="relative mt-3 text-center text-[10px] italic text-gray-600 md:text-[11px]">
          Demo preview only · No real patient data · Doctor / operator review
          required before submission.
        </p>
      </div>
    </div>
  );
}

/* ───────────────── Document sub-components (white-paper styled) ───────────────── */

function DocSection({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="relative">
      <p
        className="font-sans text-[10px] font-bold uppercase tracking-[0.08em] md:text-[11px]"
        style={{ color: DARK_BLUE }}
      >
        {label}
      </p>
      <div
        className="mt-1 h-px w-full"
        style={{ background: 'rgba(27,58,92,0.20)' }}
      />
      <div className="mt-2">{children}</div>
    </div>
  );
}

function DocTextarea({
  value,
  onChange,
  rows = 2,
}: {
  value: string;
  onChange: (v: string) => void;
  rows?: number;
}) {
  return (
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      rows={rows}
      className="w-full resize-y border border-transparent bg-transparent text-[12px] leading-relaxed text-black outline-none transition-colors hover:border-gray-200 focus:border-gray-400 md:text-[13px]"
      style={{ padding: '4px 2px' }}
    />
  );
}

function VitalRow({
  label,
  value,
  onChange,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
}) {
  return (
    <div className="flex items-center gap-3 border-b border-gray-200 py-1">
      <p
        className="w-40 shrink-0 font-sans text-[11px] uppercase tracking-[0.06em] text-gray-700 md:text-[12px]"
      >
        {label}
      </p>
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="flex-1 border-none bg-transparent p-0 text-[12px] text-black outline-none md:text-[13px]"
      />
    </div>
  );
}

function EditableList({
  items,
  onChange,
  onAdd,
  onRemove,
}: {
  items: string[];
  onChange: (i: number, v: string) => void;
  onAdd: () => void;
  onRemove: (i: number) => void;
}) {
  return (
    <div className="space-y-1.5">
      {items.map((it, i) => (
        <div key={i} className="group flex items-center gap-2 border-b border-gray-200 py-1">
          <span
            className="w-5 shrink-0 font-mono text-[10px] text-gray-500 md:text-[11px]"
          >
            {String(i + 1).padStart(2, '0')}
          </span>
          <input
            type="text"
            value={it}
            onChange={(e) => onChange(i, e.target.value)}
            className="flex-1 border-none bg-transparent p-0 text-[12px] text-black outline-none md:text-[13px]"
          />
          <button
            type="button"
            onClick={() => onRemove(i)}
            className="shrink-0 rounded-sm border border-transparent px-1.5 py-0.5 text-[10px] text-gray-400 transition-colors hover:border-gray-300 hover:text-red-600"
            aria-label={`Remove line ${i + 1}`}
          >
            <X size={11} />
          </button>
        </div>
      ))}
      <button
        type="button"
        onClick={onAdd}
        className="inline-flex items-center gap-1 rounded-sm border border-dashed px-2 py-1 font-mono text-[10px] uppercase tracking-[0.18em] text-gray-600 transition-colors hover:border-gray-400 hover:text-gray-800 md:text-[11px]"
        style={{ borderColor: '#cbd5e0' }}
      >
        <Plus size={11} />
        Add line
      </button>
    </div>
  );
}

/* ───────────────── Invoice Panel ───────────────── */

function InvoicePanel({
  pkg,
  fields,
  onOpenPrintPreview,
}: {
  pkg: Package;
  fields: ReportFields;
  onOpenPrintPreview: () => void;
}) {
  const items = splitIncluded(pkg.included);

  return (
    <div
      className="overflow-hidden rounded-sm border border-white/10 bg-navy/40 backdrop-blur-sm"
      aria-label="Package invoice preview"
    >
      {/* Outer dark chrome label band */}
      <header
        className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-2.5"
        style={{ background: 'var(--theme-badge-bg)' }}
      >
        <div className="flex items-center gap-2">
          <FileText size={14} style={{ color: 'var(--theme-badge-text)' }} />
          <p
            className="font-mono text-[10px] uppercase tracking-[0.32em]"
            style={{ color: 'var(--theme-badge-text)' }}
          >
            Package Invoice Preview
          </p>
        </div>
        <div className="flex items-center gap-3">
          <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-ice/70">
            {pkg.code}
          </p>
          <button
            type="button"
            onClick={onOpenPrintPreview}
            className="inline-flex items-center gap-1.5 rounded-sm border px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.22em] transition-colors"
            style={{
              borderColor: 'var(--theme-accent)',
              background: 'var(--theme-badge-bg)',
              color: 'var(--theme-badge-text)',
            }}
          >
            <Printer size={12} />
            Print Preview
          </button>
        </div>
      </header>

      {/* White document sheet */}
      <div className="relative bg-white p-5 text-black md:p-7">
        <DemoWatermark />

        <HMCLetterhead />

        <DocumentTitle title="Package Invoice" />

        <PatientMetaGrid
          rows={[
            {
              l1: 'Your ref.',
              v1: fields.adacRef,
              l2: 'OUR Ref No:',
              v2: fields.hmcRef,
            },
            {
              l1: 'Insurance:',
              v1: fields.toInsurance,
              l2: 'Currency:',
              v2: 'EUR',
            },
            {
              l1: 'Patient:',
              v1: fields.patientInitials,
              l2: 'Date of Birth:',
              v2: fields.dob,
            },
            {
              l1: 'Nationality:',
              v1: fields.nationality,
              l2: 'Gender:',
              v2: fields.gender,
            },
            {
              l1: 'Date of Admission:',
              v1: fields.dateOfAdmission,
              l2: 'Date of Discharge:',
              v2: fields.dateOfDischarge,
            },
            {
              l1: 'Case Type:',
              v1: 'Outpatient — Package',
              l2: 'Invoice Type:',
              v2: 'Package Invoice',
            },
          ]}
          toText={fields.toInsurance}
        />

        {/* Package code / name row */}
        <div className="relative mt-4 grid grid-cols-1 gap-3 text-[12px] md:grid-cols-2 md:text-[13px]">
          <div>
            <p
              className="font-sans text-[10px] font-bold uppercase tracking-[0.08em]"
              style={{ color: DARK_BLUE }}
            >
              Package Code
            </p>
            <p className="mt-0.5 font-mono text-[13px] font-semibold text-black md:text-[14px]">
              {pkg.code}
            </p>
          </div>
          <div>
            <p
              className="font-sans text-[10px] font-bold uppercase tracking-[0.08em]"
              style={{ color: DARK_BLUE }}
            >
              Package Name
            </p>
            <p className="mt-0.5 text-[13px] text-black md:text-[14px]">
              {pkg.name}
            </p>
          </div>
        </div>

        {/* Section bar */}
        <div
          className="relative mt-5 px-3 py-2 text-center text-[10px] font-bold uppercase tracking-[0.15em] text-white md:text-[11px]"
          style={{ background: DARK_BLUE }}
        >
          Package Inclusions
        </div>

        {/* Column header */}
        <div
          className="grid grid-cols-[40px_minmax(0,1fr)_minmax(0,1fr)_120px] items-center px-3 py-2 text-[9.5px] font-bold uppercase tracking-[0.1em] text-white md:text-[10px]"
          style={{ background: MED_BLUE }}
        >
          <span>#</span>
          <span>Item / Service</span>
          <span>Description</span>
          <span className="text-right">Billing Type</span>
        </div>

        {/* Zebra rows */}
        <div
          className="relative border-l border-r"
          style={{ borderColor: GREY_RULE }}
        >
          {items.map((it, i) => (
            <div
              key={it + i}
              className="grid grid-cols-[40px_minmax(0,1fr)_minmax(0,1fr)_120px] items-baseline gap-x-3 border-b px-3 py-2 text-[12px] md:text-[13px]"
              style={{
                background: i % 2 === 0 ? LIGHT_BLUE : '#FFFFFF',
                borderColor: GREY_RULE,
              }}
            >
              <span className="font-mono text-[10px] text-gray-700 md:text-[11px]">
                {String(i + 1).padStart(2, '0')}
              </span>
              <span className="font-medium text-black">{it}</span>
              <span className="text-gray-800">Included in package scope.</span>
              <span
                className="text-right font-mono text-[10px] uppercase tracking-[0.06em] md:text-[11px]"
                style={{ color: DARK_BLUE }}
              >
                Included
              </span>
            </div>
          ))}
        </div>

        {/* GRAND TOTAL bar — official invoice-style: DARK_BLUE full-width
            band, white bold left label, white bold right total via the
            scenario-aware InvoiceTotalValue helper (NOT PriceBadge). */}
        <div
          className="hmc-print-no-break relative mt-0 flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-white md:px-5 md:py-3.5"
          style={{ background: DARK_BLUE }}
        >
          <div>
            <p className="font-sans text-[12px] font-bold uppercase tracking-[0.18em] md:text-[13px]">
              Grand Total
            </p>
            <p className="text-[10px] italic text-white/80 md:text-[11px]">
              Single agreed package line. Per-item billing not applied.
            </p>
          </div>
          <InvoiceTotalValue pkg={pkg} />
        </div>

        {/* Transparency note */}
        <p
          className="relative mt-4 text-[11px] italic leading-relaxed text-gray-700 md:text-[12px]"
        >
          Included items are shown for transparency. Billing remains a single
          agreed package line unless escalation or out-of-scope services are
          documented separately.
        </p>

        <HMCFooter />

        <p className="relative mt-3 text-center text-[10px] italic text-gray-600 md:text-[11px]">
          Demo preview only · No real patient data · Operator-confirmed before
          dispatch in production.
        </p>
      </div>
    </div>
  );
}

/* ───────────────── Print Preview Modal ───────────────── */

function PrintPreviewModal({
  pkg,
  fields,
  onClose,
}: {
  pkg: Package;
  fields: ReportFields;
  onClose: () => void;
}) {
  // Esc closes the modal.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    document.addEventListener('keydown', onKey);
    // Lock body scroll while modal is open.
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  const handlePrint = () => {
    if (typeof window !== 'undefined') window.print();
  };

  if (typeof document === 'undefined') return null;

  return createPortal(
    <div
      className="hmc-print-root fixed inset-0 z-[80] flex items-start justify-center overflow-y-auto bg-navy-deep/85 px-4 py-10 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label="Medical report print preview"
    >
      {/* Top-right chrome — hidden in print */}
      <div className="hmc-print-controls fixed right-6 top-6 z-[81] flex gap-2">
        <button
          type="button"
          onClick={handlePrint}
          className="inline-flex items-center gap-1.5 rounded-sm border border-white/40 bg-white/10 px-3 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-white transition-colors hover:bg-white/20"
        >
          <Printer size={13} />
          Print
        </button>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close print preview"
          className="inline-flex items-center gap-1.5 rounded-sm border border-white/40 bg-white/10 px-3 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-white transition-colors hover:bg-white/20"
        >
          <X size={13} />
          Close
        </button>
      </div>

      {/* A4 sheet — read-only printable view */}
      <div
        className="hmc-print-sheet relative mx-auto w-full max-w-[860px] bg-white p-7 text-black shadow-2xl md:p-10"
      >
        <DemoWatermark />
        <HMCLetterhead />
        <DocumentTitle title="Medical Report" />
        <PatientMetaGrid
          rows={[
            {
              l1: 'Your ref.',
              v1: fields.adacRef,
              l2: 'OUR Ref No:',
              v2: fields.hmcRef,
            },
            {
              l1: 'Patient:',
              v1: fields.patientInitials,
              l2: 'Date of Birth:',
              v2: fields.dob,
            },
            {
              l1: 'Nationality:',
              v1: fields.nationality,
              l2: 'Gender:',
              v2: fields.gender,
            },
            {
              l1: 'Date of Admission:',
              v1: fields.dateOfAdmission,
              l2: 'Date of Discharge:',
              v2: fields.dateOfDischarge,
            },
            {
              l1: 'Package Code:',
              v1: pkg.code,
              l2: 'Date of Visit:',
              v2: fields.date,
            },
            {
              l1: 'Package Name:',
              v1: pkg.name,
              l2: 'Document Type:',
              v2: 'Medical Report',
            },
          ]}
          toText={fields.toInsurance}
        />

        <div className="mt-5 space-y-4">
          <ReadOnlyDocSection label="Complaint" value={fields.complaint} />
          <ReadOnlyDocSection label="Past History" value={fields.pastHistory} />
          <div>
            <p
              className="font-sans text-[10px] font-bold uppercase tracking-[0.08em] md:text-[11px]"
              style={{ color: DARK_BLUE }}
            >
              Emergency Consultation — Vital Signs
            </p>
            <div
              className="mt-1 h-px w-full"
              style={{ background: 'rgba(27,58,92,0.20)' }}
            />
            <ul className="mt-2 grid grid-cols-1 gap-y-1 text-[12px] md:grid-cols-2 md:gap-x-6 md:text-[13px]">
              <ReadOnlyVital label="Blood Pressure" value={fields.vitals.bloodPressure} />
              <ReadOnlyVital label="Pulse Rate" value={fields.vitals.pulseRate} />
              <ReadOnlyVital label="Oxygen Saturation" value={fields.vitals.oxygenSaturation} />
              <ReadOnlyVital label="Temperature" value={fields.vitals.temperature} />
              <ReadOnlyVital label="Respiratory Rate" value={fields.vitals.respiratoryRate} />
              <ReadOnlyVital label="GCS" value={fields.vitals.gcs} />
            </ul>
          </div>
          <ReadOnlyDocSection label="General Examination" value={fields.generalExamination} />
          <ReadOnlyDocSection label="Local / System Examination" value={fields.localExamination} />
          <ReadOnlyList label="Investigations" items={fields.investigations} />
          <ReadOnlyDocSection label="Diagnosis / Problem List" value={fields.diagnosis} />
          <ReadOnlyDocSection label="Management" value={fields.management} />
          <ReadOnlyDocSection label="Initial Treatment Plan" value={fields.initialTreatmentPlan} />
          <ReadOnlyList label="Medications" items={fields.medications} />
          <ReadOnlyDocSection label="Management Outcome" value={fields.managementOutcome} />
          <ReadOnlyDocSection label="Discharge Instructions" value={fields.dischargeInstructions} />
          <ReadOnlyList label="Discharge Medications" items={fields.dischargeMedications} />
          <ReadOnlyDocSection label="Follow-up Plan" value={fields.followUp} />
        </div>

        <div
          className="mt-6 border-l-2 bg-ice/60 px-3 py-2 text-[11px] leading-relaxed text-gray-700 md:text-[12px]"
          style={{ borderColor: DARK_BLUE }}
        >
          Doctor / operator review required before submission. Template
          preview; not a final clinical document.
        </div>

        <HMCFooter />

        <p className="mt-3 text-center text-[10px] italic text-gray-600 md:text-[11px]">
          Demo preview only · No real patient data · Doctor / operator review
          required before submission.
        </p>
      </div>

      <style>{PRINT_STYLE}</style>
    </div>,
    document.body
  );
}

/* ───────────────── Invoice Print Preview Modal ───────────────── */

function InvoicePrintPreviewModal({
  pkg,
  fields,
  onClose,
}: {
  pkg: Package;
  fields: ReportFields;
  onClose: () => void;
}) {
  const items = splitIncluded(pkg.included);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    document.addEventListener('keydown', onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  const handlePrint = () => {
    if (typeof window !== 'undefined') window.print();
  };

  if (typeof document === 'undefined') return null;

  return createPortal(
    <div
      className="hmc-print-root fixed inset-0 z-[80] flex items-start justify-center overflow-y-auto bg-navy-deep/85 px-4 py-10 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label="Package invoice print preview"
    >
      <div className="hmc-print-controls fixed right-6 top-6 z-[81] flex gap-2">
        <button
          type="button"
          onClick={handlePrint}
          className="inline-flex items-center gap-1.5 rounded-sm border border-white/40 bg-white/10 px-3 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-white transition-colors hover:bg-white/20"
        >
          <Printer size={13} />
          Print
        </button>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close print preview"
          className="inline-flex items-center gap-1.5 rounded-sm border border-white/40 bg-white/10 px-3 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-white transition-colors hover:bg-white/20"
        >
          <X size={13} />
          Close
        </button>
      </div>

      <div className="hmc-print-sheet relative mx-auto w-full max-w-[860px] bg-white p-7 text-black shadow-2xl md:p-10">
        <DemoWatermark />
        <HMCLetterhead />
        <DocumentTitle title="Package Invoice" />
        <PatientMetaGrid
          rows={[
            {
              l1: 'Your ref.',
              v1: fields.adacRef,
              l2: 'OUR Ref No:',
              v2: fields.hmcRef,
            },
            {
              l1: 'Insurance:',
              v1: fields.toInsurance,
              l2: 'Currency:',
              v2: 'EUR',
            },
            {
              l1: 'Patient:',
              v1: fields.patientInitials,
              l2: 'Date of Birth:',
              v2: fields.dob,
            },
            {
              l1: 'Nationality:',
              v1: fields.nationality,
              l2: 'Gender:',
              v2: fields.gender,
            },
            {
              l1: 'Date of Admission:',
              v1: fields.dateOfAdmission,
              l2: 'Date of Discharge:',
              v2: fields.dateOfDischarge,
            },
            {
              l1: 'Case Type:',
              v1: 'Outpatient — Package',
              l2: 'Invoice Type:',
              v2: 'Package Invoice',
            },
          ]}
          toText={fields.toInsurance}
        />

        <div className="mt-4 grid grid-cols-1 gap-3 text-[12px] md:grid-cols-2 md:text-[13px]">
          <div>
            <p
              className="font-sans text-[10px] font-bold uppercase tracking-[0.08em]"
              style={{ color: DARK_BLUE }}
            >
              Package Code
            </p>
            <p className="mt-0.5 font-mono text-[13px] font-semibold text-black md:text-[14px]">
              {pkg.code}
            </p>
          </div>
          <div>
            <p
              className="font-sans text-[10px] font-bold uppercase tracking-[0.08em]"
              style={{ color: DARK_BLUE }}
            >
              Package Name
            </p>
            <p className="mt-0.5 text-[13px] text-black md:text-[14px]">{pkg.name}</p>
          </div>
        </div>

        <div
          className="mt-5 px-3 py-2 text-center text-[10px] font-bold uppercase tracking-[0.15em] text-white md:text-[11px]"
          style={{ background: DARK_BLUE }}
        >
          Package Inclusions
        </div>
        <div
          className="grid grid-cols-[40px_minmax(0,1fr)_minmax(0,1fr)_120px] items-center px-3 py-2 text-[9.5px] font-bold uppercase tracking-[0.1em] text-white md:text-[10px]"
          style={{ background: MED_BLUE }}
        >
          <span>#</span>
          <span>Item / Service</span>
          <span>Description</span>
          <span className="text-right">Billing Type</span>
        </div>
        <div className="border-l border-r" style={{ borderColor: GREY_RULE }}>
          {items.map((it, i) => (
            <div
              key={it + i}
              className="grid grid-cols-[40px_minmax(0,1fr)_minmax(0,1fr)_120px] items-baseline gap-x-3 border-b px-3 py-2 text-[12px] md:text-[13px]"
              style={{
                background: i % 2 === 0 ? LIGHT_BLUE : '#FFFFFF',
                borderColor: GREY_RULE,
              }}
            >
              <span className="font-mono text-[10px] text-gray-700 md:text-[11px]">
                {String(i + 1).padStart(2, '0')}
              </span>
              <span className="font-medium text-black">{it}</span>
              <span className="text-gray-800">Included in package scope.</span>
              <span
                className="text-right font-mono text-[10px] uppercase tracking-[0.06em] md:text-[11px]"
                style={{ color: DARK_BLUE }}
              >
                Included
              </span>
            </div>
          ))}
        </div>
        <div
          className="hmc-print-no-break flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-white md:px-5 md:py-3.5"
          style={{ background: DARK_BLUE }}
        >
          <div>
            <p className="font-sans text-[12px] font-bold uppercase tracking-[0.18em] md:text-[13px]">
              Grand Total
            </p>
            <p className="text-[10px] italic text-white/80 md:text-[11px]">
              Single agreed package line. Per-item billing not applied.
            </p>
          </div>
          <InvoiceTotalValue pkg={pkg} />
        </div>

        <p className="mt-4 text-[11px] italic leading-relaxed text-gray-700 md:text-[12px]">
          Included items are shown for transparency. Billing remains a single
          agreed package line unless escalation or out-of-scope services are
          documented separately.
        </p>

        <HMCFooter />

        <p className="mt-3 text-center text-[10px] italic text-gray-600 md:text-[11px]">
          Demo preview only · No real patient data · Operator-confirmed before
          dispatch in production.
        </p>
      </div>

      <style>{PRINT_STYLE}</style>
    </div>,
    document.body
  );
}

function ReadOnlyDocSection({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p
        className="font-sans text-[10px] font-bold uppercase tracking-[0.08em] md:text-[11px]"
        style={{ color: DARK_BLUE }}
      >
        {label}
      </p>
      <div className="mt-1 h-px w-full" style={{ background: 'rgba(27,58,92,0.20)' }} />
      <p className="mt-2 whitespace-pre-wrap text-[12px] leading-relaxed text-black md:text-[13px]">
        {value || '—'}
      </p>
    </div>
  );
}

function ReadOnlyVital({ label, value }: { label: string; value: string }) {
  return (
    <li className="flex items-center gap-3 border-b border-gray-200 py-1">
      <p className="w-40 shrink-0 font-sans text-[11px] uppercase tracking-[0.06em] text-gray-700 md:text-[12px]">
        {label}
      </p>
      <p className="flex-1 text-[12px] text-black md:text-[13px]">{value || '—'}</p>
    </li>
  );
}

function ReadOnlyList({ label, items }: { label: string; items: string[] }) {
  return (
    <div>
      <p
        className="font-sans text-[10px] font-bold uppercase tracking-[0.08em] md:text-[11px]"
        style={{ color: DARK_BLUE }}
      >
        {label}
      </p>
      <div className="mt-1 h-px w-full" style={{ background: 'rgba(27,58,92,0.20)' }} />
      <ol className="mt-2 space-y-1 text-[12px] leading-relaxed text-black md:text-[13px]">
        {items.map((it, i) => (
          <li key={i} className="flex items-baseline gap-3 border-b border-gray-200 py-1">
            <span className="w-5 shrink-0 font-mono text-[10px] text-gray-500 md:text-[11px]">
              {String(i + 1).padStart(2, '0')}
            </span>
            <span className="flex-1">{it || '—'}</span>
          </li>
        ))}
      </ol>
    </div>
  );
}

/* ───────────────── Shared Patient / Case Data panel ───────────────── */

/**
 * Phase 2.4U — single edit surface for the metadata shared between the
 * medical report and the package invoice. Edits here flow into both
 * documents AND both print-preview modals because all four read from
 * the same `fields` state. The metadata grids inside the documents
 * render as read-only displays (no inline inputs) so the presenter is
 * never confused about where to type.
 */
function PatientCaseDataPanel({
  fields,
  setField,
}: {
  fields: ReportFields;
  setField: <K extends keyof ReportFields>(k: K, v: ReportFields[K]) => void;
}) {
  return (
    <section
      className="mt-6 rounded-sm border border-white/10 bg-navy/40 p-5 backdrop-blur-sm md:p-6"
      aria-label="Shared patient and case data"
    >
      <div className="mb-4 flex items-baseline justify-between gap-3">
        <p
          className="font-mono text-[10px] uppercase tracking-[0.32em]"
          style={{ color: 'var(--theme-accent)' }}
        >
          Patient / case data · shared with both documents
        </p>
        <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-ice/70">
          Edits flow live into report + invoice
        </p>
      </div>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <PanelField
          label="Patient initials"
          value={fields.patientInitials}
          onChange={(v) => setField('patientInitials', v)}
        />
        <PanelField
          label="Insurance / To"
          value={fields.toInsurance}
          onChange={(v) => setField('toInsurance', v)}
        />
        <PanelField
          label="ADAC reference"
          value={fields.adacRef}
          onChange={(v) => setField('adacRef', v)}
        />
        <PanelField
          label="HMC reference"
          value={fields.hmcRef}
          onChange={(v) => setField('hmcRef', v)}
        />
        <PanelField
          label="Nationality"
          value={fields.nationality}
          onChange={(v) => setField('nationality', v)}
        />
        <PanelField
          label="Gender"
          value={fields.gender}
          onChange={(v) => setField('gender', v)}
        />
        <PanelField
          label="Date of birth"
          type="date"
          value={fields.dob === '—' ? '' : fields.dob}
          onChange={(v) => setField('dob', v || '—')}
        />
        <PanelField
          label="Date of visit"
          type="date"
          value={fields.date}
          onChange={(v) => setField('date', v)}
        />
        <PanelField
          label="Date of admission"
          type="date"
          value={fields.dateOfAdmission}
          onChange={(v) => setField('dateOfAdmission', v)}
        />
        <PanelField
          label="Date of discharge"
          type="date"
          value={fields.dateOfDischarge}
          onChange={(v) => setField('dateOfDischarge', v)}
        />
      </div>
    </section>
  );
}

function PanelField({
  label,
  value,
  onChange,
  type = 'text',
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  type?: 'text' | 'date';
}) {
  return (
    <label className="block">
      <span className="font-mono text-[10px] uppercase tracking-[0.28em] text-ice/85">
        {label}
      </span>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 w-full rounded-sm border border-white/15 bg-navy-deep/70 px-3 py-2 text-sm text-white outline-none transition-colors focus:border-[var(--theme-accent)]"
        style={
          type === 'date'
            ? { colorScheme: 'dark' } // makes the native date picker icon readable on dark bg
            : undefined
        }
      />
    </label>
  );
}

/* ───────────────── Main component ───────────────── */

export function PackageTemplateSimulator() {
  const { applyPackages } = useOverrides();
  const { ref, inView } = useScrollReveal({ threshold: 0.05 });

  const allPackages = useMemo(
    () => applyPackages(fallbackPackagesData.packages as Package[]),
    [applyPackages]
  );
  const categories = fallbackPackagesData.categories as PackageCategory[];

  const defaultPkg =
    allPackages.find((p) => p.code === 'HMC-GI-03') ?? allPackages[0] ?? null;
  const defaultCategoryId = defaultPkg?.category ?? 1;

  const [pendingCategoryId, setPendingCategoryId] = useState<number>(defaultCategoryId);
  const [pendingPkgCode, setPendingPkgCode] = useState<string>(defaultPkg?.code ?? '');
  const [loadedPkg, setLoadedPkg] = useState<Package | null>(defaultPkg);
  const [fields, setFields] = useState<ReportFields>(() => makeDefaults(defaultPkg));
  const [printOpen, setPrintOpen] = useState(false);
  const [invoicePrintOpen, setInvoicePrintOpen] = useState(false);

  const pendingPackageOptions = useMemo(
    () => allPackages.filter((p) => p.category === pendingCategoryId),
    [allPackages, pendingCategoryId]
  );

  useEffect(() => {
    const stillValid = pendingPackageOptions.some((p) => p.code === pendingPkgCode);
    if (!stillValid && pendingPackageOptions.length > 0) {
      setPendingPkgCode(pendingPackageOptions[0].code);
    }
  }, [pendingPackageOptions, pendingPkgCode]);

  function handleLoad() {
    const next = allPackages.find((p) => p.code === pendingPkgCode);
    if (!next) return;
    setLoadedPkg(next);
    setFields(makeDefaults(next));
  }

  function setField<K extends keyof ReportFields>(key: K, value: ReportFields[K]) {
    setFields((prev) => ({ ...prev, [key]: value }));
  }

  function setVital<K extends keyof VitalsBlock>(key: K, value: string) {
    setFields((prev) => ({ ...prev, vitals: { ...prev.vitals, [key]: value } }));
  }

  function setListItem(
    key: 'investigations' | 'medications' | 'dischargeMedications',
    index: number,
    value: string
  ) {
    setFields((prev) => {
      const next = [...prev[key]];
      next[index] = value;
      return { ...prev, [key]: next };
    });
  }

  function addListItem(
    key: 'investigations' | 'medications' | 'dischargeMedications'
  ) {
    setFields((prev) => ({ ...prev, [key]: [...prev[key], ''] }));
  }

  function removeListItem(
    key: 'investigations' | 'medications' | 'dischargeMedications',
    index: number
  ) {
    setFields((prev) => ({
      ...prev,
      [key]: prev[key].filter((_, i) => i !== index),
    }));
  }

  return (
    <article ref={ref} className="mx-auto w-full max-w-7xl px-6 py-20 md:py-24">
      {/* Hero */}
      <motion.header
        initial={{ opacity: 0, y: 18 }}
        animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 18 }}
        transition={{ duration: 0.7, ease: ease.premium }}
      >
        <p
          className="font-mono text-[11px] uppercase tracking-[0.4em]"
          style={{ color: 'var(--theme-accent)' }}
        >
          §13.6 · live demo
        </p>
        <h1 className="mt-3 font-display text-4xl font-semibold leading-tight text-white md:text-5xl">
          Package Template Simulator
        </h1>
        <p className="mt-3 max-w-3xl text-base text-ice/85 md:text-lg">
          Pick a category, pick a package, click Load — the demo medical
          report template and the package invoice preview generate for that
          package. Edit any field live; nothing is saved or transmitted.
        </p>
        <div className="gold-rule mt-6 w-20" />
      </motion.header>

      {/* Controls panel */}
      <motion.section
        initial={{ opacity: 0, y: 14 }}
        animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 14 }}
        transition={{ delay: 0.15, duration: 0.7, ease: ease.premium }}
        className="mt-10 rounded-sm border border-white/10 bg-navy/40 p-5 backdrop-blur-sm md:p-6"
        aria-label="Simulator controls"
      >
        <div className="grid grid-cols-1 gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end">
          <div>
            <label className="font-mono text-[10px] uppercase tracking-[0.3em] text-ice/85">
              Category
            </label>
            <select
              value={pendingCategoryId}
              onChange={(e) => setPendingCategoryId(Number(e.target.value))}
              className="mt-2 w-full rounded-sm border border-white/15 bg-navy-deep/70 px-3 py-2.5 text-sm text-white outline-none transition-colors focus:border-[var(--theme-accent)]"
            >
              {categories.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.code} · {c.name}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="font-mono text-[10px] uppercase tracking-[0.3em] text-ice/85">
              Package
            </label>
            <select
              value={pendingPkgCode}
              onChange={(e) => setPendingPkgCode(e.target.value)}
              className="mt-2 w-full rounded-sm border border-white/15 bg-navy-deep/70 px-3 py-2.5 text-sm text-white outline-none transition-colors focus:border-[var(--theme-accent)]"
            >
              {pendingPackageOptions.map((p) => (
                <option key={p.code} value={p.code}>
                  {p.code} — {p.name}
                </option>
              ))}
            </select>
          </div>
          <button
            type="button"
            onClick={handleLoad}
            className="inline-flex h-[42px] items-center justify-center gap-2 rounded-sm border px-5 text-sm font-semibold uppercase tracking-[0.2em] transition-colors"
            style={{
              borderColor: 'var(--theme-accent)',
              background: 'var(--theme-badge-bg)',
              color: 'var(--theme-badge-text)',
            }}
          >
            <RefreshCw size={14} />
            Load Package Template
          </button>
        </div>
      </motion.section>

      {/* Loaded package banner */}
      {loadedPkg && (
        <motion.section
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: ease.premium }}
          className="mt-6 rounded-sm border p-4 backdrop-blur-sm md:p-5"
          style={{
            background: 'var(--theme-badge-bg)',
            borderColor: 'var(--theme-badge-border)',
          }}
        >
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="min-w-0">
              <p
                className="font-mono text-[10px] uppercase tracking-[0.3em]"
                style={{ color: 'var(--theme-badge-text)' }}
              >
                Currently loaded
              </p>
              <p className="mt-1 font-display text-lg text-white md:text-xl">
                {loadedPkg.code} · {loadedPkg.name}
              </p>
            </div>
            <PriceBadge pkg={loadedPkg} size="md" />
          </div>
        </motion.section>
      )}

      {/* Phase 2.4U — Shared Patient / Case Data panel above both documents.
          Single edit surface for all metadata; flows live into both the
          medical report and the package invoice (plus both print modals). */}
      {loadedPkg && <PatientCaseDataPanel fields={fields} setField={setField} />}

      {/* Two large preview documents — Phase 2.4U: report first
          (medically/operationally the service + report happens first),
          invoice second (generated from the documented service). */}
      <AnimatePresence mode="wait">
        <motion.section
          key={loadedPkg?.code ?? 'empty'}
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.5, ease: ease.premium }}
          className="mt-8 space-y-8"
        >
          {loadedPkg && (
            <>
              <ReportPanel
                pkg={loadedPkg}
                fields={fields}
                setField={setField}
                setVital={setVital}
                setListItem={setListItem}
                addListItem={addListItem}
                removeListItem={removeListItem}
                onOpenPrintPreview={() => setPrintOpen(true)}
              />
              <InvoicePanel
                pkg={loadedPkg}
                fields={fields}
                onOpenPrintPreview={() => setInvoicePrintOpen(true)}
              />
            </>
          )}
        </motion.section>
      </AnimatePresence>

      {/* Safety strip */}
      <p className="mt-10 text-center text-xs italic text-ice/70 md:text-sm">
        Demo preview only · No real patient data · Doctor / operator review
        required before submission.
      </p>

      {/* Report print preview modal */}
      {printOpen && loadedPkg && (
        <PrintPreviewModal
          pkg={loadedPkg}
          fields={fields}
          onClose={() => setPrintOpen(false)}
        />
      )}

      {/* Invoice print preview modal */}
      {invoicePrintOpen && loadedPkg && (
        <InvoicePrintPreviewModal
          pkg={loadedPkg}
          fields={fields}
          onClose={() => setInvoicePrintOpen(false)}
        />
      )}
    </article>
  );
}
